[project]
name = "t25-4m-mlops"
version = "0.1.0"
requires-python = ">=3.11,<3.12"

[project.optional-dependencies]
gateway = [
  "fastapi==0.135.2",
  "uvicorn==0.42.0",
  "pydantic==2.12.5",
  "httpx==0.28.1",
  "psycopg[binary]==3.3.3",
  "python-multipart==0.0.22",
  "boto3==1.42.78",
]
gateway-dev = [
  "pytest==9.0.2",
  "pytest-cov==7.1.0",
  "black==26.3.1",
  "flake8==7.3.0",
  "isort==8.0.1",
  "mypy==1.19.1",
  "pylint==4.0.5",
]
inference = [
  "fastapi==0.135.2",
  "uvicorn==0.42.0",
  "pydantic==2.12.5",
  "joblib==1.5.3",
  "boto3==1.42.78",
  "scikit-learn==1.8.0",
  "pandas==3.0.1",
  "lightgbm==4.6.0",
  "httpx==0.28.1",
]
inference-dev = [
  "pytest==9.0.2",
  "pytest-cov==7.1.0",
  "black==26.3.1",
  "flake8==7.3.0",
  "isort==8.0.1",
  "mypy==1.19.1",
  "pylint==4.0.5",
]

[tool.black]
line-length = 88
target-version = ["py311"]
include = '\.pyi?$'
extend-exclude = '''
/(
  \.git
  | \.mypy_cache
  | \.pytest_cache
  | \.venv
  | htmlcov
)/
'''

[tool.isort]
profile = "black"
line_length = 88
py_version = 311
skip_gitignore = true
src_paths = ["config", "services/gateway-service/src", "services/inference-service/src"]

[tool.pylint.main]
py-version = "3.11"
ignore-paths = [
  "^htmlcov/.*$",
]

[tool.pylint.messages_control]
disable = [
  "missing-module-docstring",
  "missing-class-docstring",
  "missing-function-docstring",
  "too-few-public-methods",
  "duplicate-code",
  "import-error",
  "wrong-import-position",
  "import-outside-toplevel",
  "unused-argument",
  "too-many-positional-arguments",
]

[tool.pylint.format]
max-line-length = 88

[tool.pylint.design]
max-args = 8
max-attributes = 12

[tool.pylint.similarities]
min-similarity-lines = 6
