apiVersion: v1
kind: ConfigMap
metadata:
  name: mlops-shared-config
  namespace: mlops-app
data:
  GATEWAY_PORT: "8000"
  INFERENCE_PORT: "8001"
  INFERENCE_SERVICE_URL: "http://inference-service.mlops-app.svc.cluster.local:8001"
  AIRFLOW_INFERENCE_BASE_URL: "http://inference-service.mlops-app.svc.cluster.local:8001"
  AWS_DEFAULT_REGION: "us-east-1"
  DATASET_UPLOADS_BUCKET: "ml-artifacts"
  DATASET_UPLOADS_PREFIX: "inference/uploads"
  RETRAIN_SOURCE_DATASETS_BUCKET: "ml-artifacts"
  RETRAIN_SOURCE_DATASETS_PREFIX: "training/uploads"
  RETRAIN_NON_PROMOTED_PREFIX: "training/non-promoted"
  PREDICTION_RESULTS_BUCKET: "ml-artifacts"
  PREDICTION_RESULTS_PREFIX: "inference/results"
  SEGMENT_RESULTS_BUCKET: "ml-artifacts"
  SEGMENT_RESULTS_PREFIX: "inference/segments"
  S3_SSE_MODE: "aws:kms"
  S3_SSE_KMS_KEY_ID: "datasets-key"
  REQUIRE_UPLOAD_ENCRYPTION: "true"
  AIRFLOW_K8S_NAMESPACE: "mlops-app"
  AIRFLOW_K8S_SERVICE_ACCOUNT: "airflow-runner"
