apiVersion: v1
kind: Secret
metadata:
  name: mlops-app-secrets
  namespace: mlops-app
type: Opaque
stringData:
  SERVICE_API_KEY: "change-me"
  GATEWAY_DATABASE_URL: "postgresql://postgres:change-me@postgres.mlops-data.svc.cluster.local:5432/gateway_db"
  S3_ENDPOINT_URL: "https://minio.mlops-data.svc.cluster.local:9000"
  AWS_ACCESS_KEY_ID: "change-me"
  AWS_SECRET_ACCESS_KEY: "change-me"
  POSTGRES_DB: "gateway_db"
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "change-me"
  MINIO_ROOT_USER: "minioadmin"
  MINIO_ROOT_PASSWORD: "change-me"
---
apiVersion: v1
kind: Secret
metadata:
  name: minio-kes-secrets
  namespace: mlops-data
type: Opaque
stringData:
  MINIO_KMS_KES_KEY_NAME: "datasets-key"
  MINIO_KMS_KES_ENDPOINT: "https://kes.mlops-sec.svc.cluster.local:7373"
  MINIO_KMS_KES_CERT_FILE: "/certs/public.crt"
  MINIO_KMS_KES_KEY_FILE: "/certs/private.key"
  MINIO_KMS_KES_CAPATH: "/certs/ca.crt"
